/* Boundary import, replacement, persistence, transform, and export debugger. */
let boundaryDebugFileDefaults=null;
async function boundaryDebugLoadDefaultFile(){if(boundaryDebugFileDefaults!==null)return boundaryDebugFileDefaults;try{const response=await fetch("mena-boundary-debug.json",{cache:"no-store"});boundaryDebugFileDefaults=response.ok?await response.json():{}}catch{boundaryDebugFileDefaults={}}return boundaryDebugFileDefaults}
function boundaryDebugReadStore(){try{const value=JSON.parse(localStorage.getItem(BOUNDARY_DEBUG_STORAGE)||"{}");return value&&typeof value==="object"?value:{}}catch{return{}}}
function boundaryDebugInitialStore(){const local=boundaryDebugReadStore();return Object.keys(local).length?local:(boundaryDebugFileDefaults&&typeof boundaryDebugFileDefaults==="object"?boundaryDebugFileDefaults:{})}
function boundaryDebugLoadStore(value=boundaryDebugInitialStore()){boundaryDebugTransforms=value.transforms&&typeof value.transforms==="object"?value.transforms:{};boundaryDebugImported=Array.isArray(value.imported)?value.imported.filter(item=>item&&Array.isArray(item.paths)):[];boundaryDebugReplacements=value.replacements&&typeof value.replacements==="object"?value.replacements:{};const staleHejazTransformKeys=Object.keys(boundaryDebugTransforms).filter(key=>/^period:\d{4}-\d{4}::hejaz$/.test(key));staleHejazTransformKeys.forEach(key=>delete boundaryDebugTransforms[key]);const staleHejazDraft=Object.prototype.hasOwnProperty.call(boundaryDebugDrafts,"current:hejaz");delete boundaryDebugDrafts["current:hejaz"];const importedChanged=boundaryDebugNormalizeImportedItems(),replacementChanged=boundaryDebugNormalizeReplacements(),legacySaved=Array.isArray(value.saved)&&value.saved.length>0;if(importedChanged||replacementChanged||legacySaved||staleHejazTransformKeys.length>0||staleHejazDraft)boundaryDebugPersist()}
function boundaryDebugStoreValue(){return{version:2,updatedAt:new Date().toISOString(),year:Number(dom.year.value),transforms:boundaryDebugTransforms,imported:boundaryDebugImported,replacements:boundaryDebugReplacements}}
function boundaryDebugPersist(){try{localStorage.setItem(BOUNDARY_DEBUG_STORAGE,JSON.stringify(boundaryDebugStoreValue()))}catch{return false}return true}
function boundaryDebugId(prefix="boundary"){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function boundaryDebugTargetMeta(value=boundaryDebugTarget){const [type,...rest]=String(value||"").split(":");const id=rest.join(":");return type&&id?{type,id,value}:null}
function boundaryDebugItemFor(target){if(!target||target.type!=="imported")return null;return boundaryDebugImported.find(item=>item.key===target.id)||null}
function boundaryDebugPathFileSignature(paths){return JSON.stringify((paths||[]).map(record=>({d:String(record?.d||"").trim().replace(/\s+/g," "),fillRule:record?.fillRule||"nonzero",cutoutPaths:(record?.cutoutPaths||[]).map(path=>String(path).trim().replace(/\s+/g," "))})))}
function boundaryDebugImportedSignature(item){return boundaryDebugPathFileSignature(item?.paths)}
function boundaryDebugRemapImportedReference(fromKey,toKey){Object.entries(boundaryDebugReplacements).forEach(([key,value])=>{if(typeof value==="string"){if(value==="imported:"+fromKey)boundaryDebugReplacements[key]="imported:"+toKey}else if(value?.type==="imported"&&value.key===fromKey)value.key=toKey})}
function boundaryDebugNormalizeImportedItems(){let changed=false;const seen=new Map(),next=[];boundaryDebugImported.forEach(item=>{const signature=boundaryDebugImportedSignature(item);if(!signature){next.push(item);return}item.signature=signature;const existing=seen.get(signature);if(existing){if(item.key!==existing.key){boundaryDebugRemapImportedReference(item.key,existing.key);changed=true}return}seen.set(signature,item);next.push(item)});boundaryDebugImported=next;return changed}
function boundaryDebugReplacementKeyInfo(key){const period=String(key).match(/^period:(\d+)-(\d+)::(.+)$/);if(period)return{kind:"period",from:Number(period[1]),to:Number(period[2]),id:period[3]};const legacy=String(key).match(/^(\d{4})::(.+)$/);return legacy?{kind:"legacy",from:Number(legacy[1]),to:Number(legacy[1]),id:legacy[2]}:null}
function boundaryDebugReplacementTargetId(id,y){return boundaryDebugCanonicalId(id,y)||id}
function boundaryDebugReplacementPeriodFor(id,y=Number(dom.year.value)){const period=boundaryDebugPeriodFor(id,Number(y));return period&&period.from!==undefined?period:{name:boundaryDebugNameAt(boundaryDebugReplacementTargetId(id,y),Number(y)),from:Number(y),to:Number(y)}}
function boundaryDebugReplacementKey(id,y=Number(dom.year.value)){const targetId=boundaryDebugReplacementTargetId(id,y),period=boundaryDebugReplacementPeriodFor(id,y);return "period:"+period.from+"-"+period.to+"::"+targetId}
function boundaryDebugNormalizeReplacements(){let changed=false;const normalized={};Object.entries(boundaryDebugReplacements).forEach(([key,value])=>{const info=boundaryDebugReplacementKeyInfo(key);if(!info){normalized[key]=value;return}const period={name:boundaryDebugNameAt(boundaryDebugReplacementTargetId(info.id,info.from),info.from),from:info.from,to:info.to},resolved=boundaryDebugReplacementItemTarget(value);if(resolved?.item)boundaryDebugApplyImportedPeriod(resolved.item,period);if(info.kind!=="legacy"){normalized[key]=value;return}const nextKey=boundaryDebugReplacementKey(info.id,info.from);if(nextKey!==key)changed=true;normalized[nextKey]=value&&typeof value==="object"?{...value,period}:value});if(changed)boundaryDebugReplacements=normalized;return changed}
function boundaryDebugReplacementItemTarget(value){const target=typeof value==="string"?boundaryDebugTargetMeta(value):value?.type?{type:value.type,id:value.key||value.id,value:value.type+":"+ (value.key||value.id)}:{type:"imported",id:value?.key||value?.id,value:"imported:"+ (value?.key||value?.id)};return target?{target,item:boundaryDebugItemFor(target)}:null}
function boundaryDebugHasReplacementForYear(y){return boundaryDebugReplacementEntriesForYear(Number(y)).length>0}
function boundaryDebugApplyImportedPeriod(item,period,fileName){if(!item||!period||period.from===undefined)return item;item.periods=Array.isArray(item.periods)?item.periods:[];if(!item.periods.some(entry=>entry&&entry.from===period.from&&entry.to===period.to))item.periods.push({...period});const samePeriod=!item.period||item.period.from===period.from&&item.period.to===period.to;if(samePeriod){item.period={...period};item.year=period.from;if(!item.name||!item.sourceFile||item.name===boundaryDebugImportName(item.sourceFile)||item.name===item.id)item.name=boundaryDebugFileNameForPeriod(period)}if(fileName)item.sourceFile=fileName;return item}
function boundaryDebugReplacementEntriesForYear(y){const year=Number(y),entries=new Map();Object.entries(boundaryDebugReplacements).forEach(([key,value])=>{const info=boundaryDebugReplacementKeyInfo(key);if(!info||year<info.from||year>info.to)return;const resolved=boundaryDebugReplacementItemTarget(value),item=resolved?.item;if(item?.paths?.length)entries.set(info.id,{id:info.id,item,key,period:{name:boundaryDebugNameAt(boundaryDebugReplacementTargetId(info.id,info.from),info.from),from:info.from,to:info.to}})});return[...entries.values()]}
function boundaryDebugStorageKey(target,y=Number(dom.year.value)){return target?.type==="current"?boundaryDebugReplacementKey(target.id,y):target?.id||""}
function boundaryDebugLegacyStorageKey(target,y=Number(dom.year.value)){return target?.type==="current"?String(y)+"::"+target.id:target?.id||""}
// The filename range must describe an unchanged SVG geometry, not merely a
// formal-name interval. CShapes has annual cohorts and the Ottoman outline in
// particular changes around 1913 and 1918, so compare exact path data for each
// adjacent year before creating a shared period.
function boundaryDebugCanonicalId(id,y){if(id==="ottoman")return y<=1922?"ottoman":null;return id==="turkey"&&y<=1922?"ottoman":id}
function boundaryDebugSourceId(canonical){return canonical==="ottoman"?"turkey":canonical}
function boundaryDebugFeaturesForYear(y){if(!boundaryDebugFeatureCache[y])boundaryDebugFeatureCache[y]=y>=1886?boundaryFeaturesForYear(y):null;return boundaryDebugFeatureCache[y]||[]}
function boundaryDebugPathRecordsForYear(id,y){
  const canonical=boundaryDebugCanonicalId(id,y);
  if(!canonical)return[];
  const records=[];
  const dispute=typeof disputeRegionForYear==="function"&&disputeRegionForYear(canonical,y);
  if(dispute){const reference=canonical==="sinai-peninsula"?window.MENA_SINAI_REFERENCE:canonical==="golan-heights"?window.MENA_GOLAN_REFERENCE:null;return[{id:canonical,d:reference?.path||dispute.path,fillRule:reference?.fillRule||"evenodd",cutoutPaths:[]}]}
  if(y>=1886){
    boundaryDebugFeaturesForYear(y).forEach(feature=>{
      const logicalId=feature.id==="turkey"&&y<=1922?"ottoman":feature.id;
      if(logicalId!==canonical||!feature.path)return;
      records.push({
        id:logicalId,
        d:feature.path,
        fillRule:logicalId==="ottoman"?"evenodd":feature.source?.includes("extension")?"nonzero":"evenodd",
        cutoutPaths:Array.isArray(feature.cutoutPaths)?[...feature.cutoutPaths]:[]
      });
    });
  }else{
    const sourceId=boundaryDebugSourceId(canonical);
    dom.schematicCountries.filter(path=>path.dataset.id===sourceId).forEach((path,index)=>records.push({
      id:canonical,
      d:path.getAttribute("d")||"",
      fillRule:path.getAttribute("fill-rule")||"nonzero",
      cutoutPaths:[]
    }));
  }
  return records.filter(record=>record.d);
}
function boundaryDebugPathSignature(records){return JSON.stringify(records.map(record=>({id:record.id,d:record.d,fillRule:record.fillRule||"nonzero",cutoutPaths:record.cutoutPaths||[]})))}
function boundaryDebugGeometryForYear(id,y){
  const canonical=boundaryDebugCanonicalId(id,y);
  if(!canonical)return{canonical:null,records:[],signature:""};
  const key=`${y}:${canonical}`;
  if(boundaryDebugGeometryCache[key])return boundaryDebugGeometryCache[key];
  const records=boundaryDebugPathRecordsForYear(canonical,y),value={canonical,records,signature:records.length?boundaryDebugPathSignature(records):""};
  boundaryDebugGeometryCache[key]=value;
  return value;
}
function boundaryDebugNameAt(canonical,y){
  const periods=window.MENA_FORMAL_NAMES?.[canonical]||[],hit=periods.find(([from,to])=>y>=from&&y<=to);
  if(hit)return hit[2];
  const fallback=countryEra(canonical,y);
  return fallback?.[2]||meta[canonical]?.[0]||canonical;
}
function boundaryDebugPeriodFor(id,y){
  const canonical=boundaryDebugCanonicalId(id,y),year=Number(y);
  if(!canonical)return{name:id,from:year,to:year};
  const current=boundaryDebugGeometryForYear(canonical,year),signature=current.signature;
  if(!signature)return{name:boundaryDebugNameAt(canonical,year),from:year,to:year};
  let from=year,to=year;
  for(let candidate=year-1;candidate>=1797;candidate--){
    if(boundaryDebugCanonicalId(id,candidate)!==canonical)break;
    const previous=boundaryDebugGeometryForYear(canonical,candidate);
    if(!previous.signature||previous.signature!==signature)break;
    from=candidate;
  }
  for(let candidate=year+1;candidate<=2026;candidate++){
    if(boundaryDebugCanonicalId(id,candidate)!==canonical)break;
    const next=boundaryDebugGeometryForYear(canonical,candidate);
    if(!next.signature||next.signature!==signature)break;
    to=candidate;
  }
  // Use the first year's formal name as the stable stem when a name change
  // happens without a geometry change. Geometry, not nomenclature, owns the
  // shared-file interval.
  return{name:boundaryDebugNameAt(canonical,from),from,to}
}
function boundaryDebugRebuildMapForReplacement(y){selected=null;clearMapState();if(!realMode){boundaryKey=boundaryKeyFor(y);boundaryDebugRenderLayer(y);return}dom.realRoot.classList.add("updating");buildBoundaryMap(y);boundaryKey=boundaryKeyFor(y);createLabels();historicalStyles(y);syncFlags(y);requestAnimationFrame(()=>{if(realMode&&+dom.year.value===y)dom.realRoot.classList.remove("updating")});boundaryDebugRenderLayer(y)}
function boundaryDebugPeriodLabel(period){return period&&period.from!==undefined?`${period.name} ${period.from}-${period.to}`:period?.name||"疆域"}
function boundaryDebugFileNameForPeriod(period){return period&&period.from!==undefined?String(period.name||"疆域")+period.from+"-"+period.to:period?.name||"疆域"}
function boundaryDebugFileStem(item){const period=item?.period;if(period&&period.from!==undefined)return`${period.name}${period.from}-${period.to}`;return`${item?.name||"疆域"}${item?.year??Number(dom.year.value)}`}
function boundaryDebugDefaultsFor(target){return target?.id==="hejaz"?{...boundaryDebugDefaults,offsetX:1}:{...boundaryDebugDefaults}}
function boundaryDebugSettings(target,y=Number(dom.year.value)){const item=boundaryDebugItemFor(target),legacy=boundaryDebugTransforms[boundaryDebugLegacyStorageKey(target,y)]||{},shared=boundaryDebugTransforms[boundaryDebugStorageKey(target,y)]||{};return{...boundaryDebugDefaultsFor(target),...(item?.transform||{}),...legacy,...shared,...(boundaryDebugDrafts[target?.value]||{})}}
function boundaryDebugReadForm(){return{scaleX:Number(dom.boundaryDebugScaleX.value)||1,scaleY:Number(dom.boundaryDebugScaleY.value)||1,offsetX:Number(dom.boundaryDebugOffsetX.value)||0,offsetY:Number(dom.boundaryDebugOffsetY.value)||0,rotation:Number(dom.boundaryDebugRotation.value)||0,opacity:Number(dom.boundaryDebugOpacity.value)||.72}}
function boundaryDebugWriteForm(settings){const value={...boundaryDebugDefaults,...settings};[[dom.boundaryDebugScaleX,dom.boundaryDebugScaleXNumber],[dom.boundaryDebugScaleY,dom.boundaryDebugScaleYNumber],[dom.boundaryDebugOffsetX,dom.boundaryDebugOffsetXNumber],[dom.boundaryDebugOffsetY,dom.boundaryDebugOffsetYNumber],[dom.boundaryDebugRotation,dom.boundaryDebugRotationNumber],[dom.boundaryDebugOpacity,dom.boundaryDebugOpacityNumber]].forEach(([range,number],index)=>{const key=["scaleX","scaleY","offsetX","offsetY","rotation","opacity"][index],next=String(value[key]);if(range)range.value=next;if(number)number.value=next});boundaryDebugUpdateOutputs()}
function boundaryDebugUpdateOutputs(){[[dom.boundaryDebugScaleX,"#boundaryDebugScaleXValue",v=>`${Number(v).toFixed(2)}×`],[dom.boundaryDebugScaleY,"#boundaryDebugScaleYValue",v=>`${Number(v).toFixed(2)}×`],[dom.boundaryDebugOffsetX,"#boundaryDebugOffsetXValue",v=>String(v)],[dom.boundaryDebugOffsetY,"#boundaryDebugOffsetYValue",v=>String(v)],[dom.boundaryDebugRotation,"#boundaryDebugRotationValue",v=>`${Number(v).toFixed(1)}°`],[dom.boundaryDebugOpacity,"#boundaryDebugOpacityValue",v=>`${Math.round(Number(v)*100)}%`]].forEach(([input,selector,format])=>{const output=$(selector);if(output)output.textContent=format(input.value)})}
function boundaryDebugPathRecordsBounds(records){const boxes=records.map(record=>record?.d?pathDataBox(record.d):null).filter(Boolean);if(!boxes.length)return{x:0,y:0,width:0,height:0};const left=Math.min(...boxes.map(box=>box.x)),top=Math.min(...boxes.map(box=>box.y)),right=Math.max(...boxes.map(box=>box.x+box.width)),bottom=Math.max(...boxes.map(box=>box.y+box.height));return{x:left,y:top,width:right-left,height:bottom-top}}
function boundaryDebugTransform(anchor,settings){const cx=anchor.x+anchor.width/2,cy=anchor.y+anchor.height/2;return`translate(${cx+(Number(settings.offsetX)||0)} ${cy+(Number(settings.offsetY)||0)}) rotate(${Number(settings.rotation)||0}) scale(${Number(settings.scaleX)||1} ${Number(settings.scaleY)||1}) translate(${-cx} ${-cy})`}
function boundaryDebugProjectPoint(point){const lon=Number(point?.[0]),lat=Math.max(-85,Math.min(85,Number(point?.[1])));if(!Number.isFinite(lon)||!Number.isFinite(lat))return null;const west=-18,east=63,north=43,south=7,left=58,right=1040,top=55,bottom=530;const mercator=v=>Math.log(Math.tan(Math.PI/4+v*Math.PI/360));const northY=mercator(north),southY=mercator(south);return[left+(lon-west)/(east-west)*(right-left),top+(northY-mercator(lat))/(northY-southY)*(bottom-top)]}
function boundaryDebugRingPath(ring){const points=(ring||[]).map(boundaryDebugProjectPoint).filter(Boolean);return points.length>=3?points.map((point,index)=>`${index?"L":"M"}${point[0].toFixed(2)},${point[1].toFixed(2)}`).join("")+"Z":""}
function boundaryDebugGeometryPaths(geometry){if(!geometry)return[];if(geometry.type==="Polygon")return(geometry.coordinates||[]).map(boundaryDebugRingPath).filter(Boolean).map(d=>({d,fillRule:"evenodd"}));if(geometry.type==="MultiPolygon")return(geometry.coordinates||[]).flatMap(coordinates=>boundaryDebugGeometryPaths({type:"Polygon",coordinates}));if(geometry.type==="GeometryCollection")return(geometry.geometries||[]).flatMap(boundaryDebugGeometryPaths);return[]}
function boundaryDebugFeatureItem(feature,index,prefix="imported"){const props=feature.properties||{},paths=boundaryDebugGeometryPaths(feature.geometry),id=String(feature.id||props.id||props.iso_a3||props.name||`${prefix}-${index}`);return paths.length?{key:boundaryDebugId(prefix),id,name:String(props.name_zh||props.name||props.NAME||id),year:null,source:String(props.source||"GeoJSON 导入"),paths}:null}
function boundaryDebugImportName(fileName){const raw=String(fileName||"").split(/[\\/]/).pop()||"导入疆域";const stem=raw.replace(/\.[^.]+$/i,"").trim();return stem||"导入疆域"}
function boundaryDebugParseSvg(text,fileName){const doc=new DOMParser().parseFromString(text,"image/svg+xml"),paths=[...doc.querySelectorAll("path[d]")].map(path=>({d:path.getAttribute("d")||"",fillRule:path.getAttribute("fill-rule")||"nonzero"})).filter(record=>record.d),name=boundaryDebugImportName(fileName);return paths.length?[{key:boundaryDebugId("imported"),id:`svg-${name}`,name,year:null,source:`${name} · SVG 文件`,paths}]:[]}
function boundaryDebugParseJson(value){if(value?.version&&Array.isArray(value.imported)){boundaryDebugLoadStore(value);return{config:true,items:[]}}if(["Polygon","MultiPolygon","GeometryCollection"].includes(value?.type))return{config:false,items:[boundaryDebugFeatureItem({type:"Feature",properties:{},geometry:value},0,"geometry")].filter(Boolean)};const features=value?.type==="FeatureCollection"?value.features:value?.type==="Feature"?[value]:null;if(Array.isArray(features))return{config:false,items:features.map((feature,index)=>boundaryDebugFeatureItem(feature,index)).filter(Boolean)};const records=Array.isArray(value)?value:[value];const items=records.map((item,index)=>{const paths=Array.isArray(item?.paths)?item.paths.map(path=>typeof path==="string"?{d:path}:{d:path?.d||path?.path,fillRule:path?.fillRule||"nonzero"}).filter(path=>path.d):(item?.path||item?.d)?[{d:item.path||item.d,fillRule:item.fillRule||"nonzero"}]:[];return paths.length?{key:boundaryDebugId("imported"),id:String(item.id||`json-${index+1}`),name:String(item.name||item.name_zh||item.id||`JSON 路径 ${index+1}`),year:item.year??null,source:String(item.source||"JSON 路径导入"),paths}:null}).filter(Boolean);return{config:false,items}}
function boundaryDebugParseImport(text,fileName){const extension=String(fileName||"").toLowerCase().split(".").pop();if(extension==="svg"||/\<svg[\s\S]*\<path/i.test(text))return{config:false,items:boundaryDebugParseSvg(text,fileName)};const source=extension==="js"?text.slice(text.indexOf("["),text.lastIndexOf("]")+1):text;try{return boundaryDebugParseJson(JSON.parse(source),fileName)}catch(error){throw new Error("文件不是有效的 SVG、GeoJSON、JSON 或地图数据 JS 文件")}}
function boundaryDebugImportItem(parsed,fileName){const paths=(parsed.items||[]).flatMap(item=>item.paths||[]).filter(path=>path?.d),name=boundaryDebugImportName(fileName),signature=boundaryDebugPathFileSignature(paths);if(!paths.length)return null;const existing=boundaryDebugImported.find(item=>boundaryDebugImportedSignature(item)===signature);if(existing){existing.signature=signature;return existing}return{key:boundaryDebugId("imported"),id:"file-"+name,name,year:null,source:(fileName||name)+" · 导入",sourceFile:fileName||name,signature,paths}}
function boundaryDebugPopulateTargets(preserve=true){const previous=preserve?(dom.boundaryDebugTarget.value||boundaryDebugTarget):"",y=Number(dom.year.value);dom.boundaryDebugTarget.innerHTML="";const addGroup=(label,entries)=>{if(!entries.length)return;const group=document.createElement("optgroup");group.label=label;entries.forEach(entry=>{const option=document.createElement("option");option.value=entry.value;option.textContent=entry.label;group.append(option)});dom.boundaryDebugTarget.append(group)};const currentIds=[...new Set(activeCountries().map(path=>path.dataset.id))];addGroup(`当前地图 · ${y}`,currentIds.map(id=>{const period=boundaryDebugPeriodFor(id,y);return{value:`current:${id}`,label:boundaryDebugPeriodLabel(period)}}));const option=[...dom.boundaryDebugTarget.options].find(item=>item.value===previous)||[...dom.boundaryDebugTarget.options].find(item=>item.value===boundaryDebugTarget)||dom.boundaryDebugTarget.options[0];if(option){dom.boundaryDebugTarget.value=option.value;boundaryDebugTarget=option.value;boundaryDebugLoadForm()}}
function boundaryDebugLoadForm(){const target=boundaryDebugTargetMeta(dom.boundaryDebugTarget?.value||boundaryDebugTarget);if(!target){dom.boundaryDebugCurrent.textContent=`当前年份：${dom.year.value} · 没有可调试对象`;return}boundaryDebugTarget=target.value;const period=boundaryDebugPeriodFor(target.id,Number(dom.year.value));boundaryDebugWriteForm(boundaryDebugSettings(target));dom.boundaryDebugCurrent.textContent=`${boundaryDebugPeriodLabel(period)} · 当前疆域调试`;boundaryDebugRenderLayer(Number(dom.year.value))}
function boundaryDebugRefreshDraft(){const target=boundaryDebugTargetMeta(dom.boundaryDebugTarget?.value||boundaryDebugTarget);if(!target)return;boundaryDebugTarget=target.value;boundaryDebugDrafts[target.value]=boundaryDebugReadForm();boundaryDebugUpdateOutputs();boundaryDebugRenderLayer(Number(dom.year.value))}
function boundaryDebugCommit(){const target=boundaryDebugTargetMeta(dom.boundaryDebugTarget?.value||boundaryDebugTarget);if(!target)return false;boundaryDebugTransforms[boundaryDebugStorageKey(target)]=boundaryDebugReadForm();boundaryDebugDrafts[target.value]={...boundaryDebugTransforms[boundaryDebugStorageKey(target)]};const ok=boundaryDebugPersist();boundaryDebugRenderLayer(Number(dom.year.value));return ok}
function boundaryDebugCapturePaths(elements){return elements.map((element,index)=>({d:element.getAttribute("d")||"",fillRule:element.getAttribute("fill-rule")||"nonzero",id:element.dataset.id||`part-${index}`,cutoutPaths:(()=>{try{const value=JSON.parse(element.dataset.cutoutPaths||"[]");return Array.isArray(value)?value:[]}catch{return[]}})()})).filter(record=>record.d)}
function boundaryDebugDisputeElement(id){return dom.frontierOverlays?.querySelector(`.dispute-hit[data-dispute-id="${id}"]`)||null}
function boundaryDebugCurrentElements(id,y,all=false){const elements=all?[...activeCountries()]:activeCountries().filter(path=>path.dataset.id===id);const disputeIds=typeof disputeRegionIdsForYear==="function"?(all?disputeRegionIdsForYear(y):[id]):[];disputeIds.forEach(disputeId=>{const element=boundaryDebugDisputeElement(disputeId);if(element&&!elements.includes(element))elements.push(element)});return elements}
function boundaryDebugAppendItem(item,settings,className){const ns="http://www.w3.org/2000/svg",group=document.createElementNS(ns,"g"),anchor=boundaryDebugPathRecordsBounds(item.paths);group.classList.add(className);group.setAttribute("opacity",String(settings.opacity));group.setAttribute("transform",boundaryDebugTransform(anchor,settings));item.paths.forEach(record=>{const path=document.createElementNS(ns,"path");path.setAttribute("d",record.d);path.setAttribute("fill-rule",record.fillRule||"nonzero");group.append(path)});dom.boundaryDebugLayer.append(group)}
function boundaryDebugRenderSchematicReplacements(y){const entries=realMode?[]:boundaryDebugReplacementEntriesForYear(y),ids=new Set(entries.map(entry=>entry.id));dom.schematicCountries.forEach(path=>path.classList.toggle("boundary-debug-replaced-source",ids.has(path.dataset.id)));if(!entries.length)return;entries.forEach(({id,item})=>{const target={type:"current",id,value:`current:${id}`},settings=boundaryDebugSettings(target,y);boundaryDebugAppendItem(item,settings,"boundary-debug-schematic-replacement")})}
function boundaryDebugExportTarget(){const target=boundaryDebugTargetMeta(dom.boundaryDebugTarget?.value||boundaryDebugTarget);if(!target||target.type!=="current")return null;const y=Number(dom.year.value),paths=boundaryDebugCapturePaths(boundaryDebugCurrentElements(target.id,y)),period=boundaryDebugPeriodFor(target.id,y);return paths.length?{paths,name:period.name,period,source:"现有地图 SVG",year:y,settings:boundaryDebugSettings(target,y)}:null}
function boundaryDebugEscapeXml(value){return String(value).replace(/[&<>"']/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&apos;"}[character]))}
function boundaryDebugDownload(content,fileName,type){const url=URL.createObjectURL(new Blob([content],{type})),anchor=document.createElement("a");anchor.href=url;anchor.download=fileName;anchor.style.display="none";document.body.append(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),0)}
function boundaryDebugExportGeometryForItem(format,item){if(!item){dom.boundaryDebugStatus.textContent="请先选择要导出的疆域。";return}const anchor=boundaryDebugPathRecordsBounds(item.paths),transform=boundaryDebugTransform(anchor,item.settings),safeName=boundaryDebugFileStem(item).replace(/[\\/:*?"<>|]/g,"-").replace(/\s+/g,"_")||"boundary",year=item.year??Number(dom.year.value);if(format==="svg"){const cutouts=item.paths.flatMap(record=>record.cutoutPaths||[]),mask=cutouts.length?`<defs><mask id="boundaryCutoutMask" mask-type="luminance" maskUnits="userSpaceOnUse" maskContentUnits="userSpaceOnUse" x="0" y="0" width="1080" height="650"><rect x="0" y="0" width="1080" height="650" fill="white"/>${cutouts.map(path=>`<path d="${boundaryDebugEscapeXml(path)}" fill="black" fill-rule="nonzero"/>`).join("")}</mask></defs>`:"",paths=item.paths.map(record=>`<path data-id="${boundaryDebugEscapeXml(record.id||"")}" d="${boundaryDebugEscapeXml(record.d)}" fill-rule="${boundaryDebugEscapeXml(record.fillRule||"nonzero")}"${record.cutoutPaths?.length?' mask="url(#boundaryCutoutMask)"':''}/>`).join("");const svg=`<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1080 650"><title>${boundaryDebugEscapeXml(item.name)}</title>${mask}<g transform="${boundaryDebugEscapeXml(transform)}" opacity="${Number(item.settings.opacity)||.72}" fill="#a43b2f" stroke="#54231d" stroke-width="1.5">${paths}</g></svg>\n`;boundaryDebugDownload(svg,`${safeName}.svg`,`image/svg+xml;charset=utf-8`);dom.boundaryDebugStatus.textContent=`已导出 ${safeName}.svg。`;return}const payload={version:1,type:"boundary-paths",name:item.name,period:item.period||null,year,source:item.source,coordinateSpace:"svg-viewBox",viewBox:[0,0,1080,650],transform:item.settings,paths:item.paths};boundaryDebugDownload(JSON.stringify(payload,null,2),`${safeName}.json`,`application/json;charset=utf-8`);dom.boundaryDebugStatus.textContent=`已导出 ${safeName}.json。`}
function boundaryDebugExportGeometry(format){boundaryDebugExportGeometryForItem(format,boundaryDebugExportTarget())}
function boundaryDebugExportAllSvg(){const y=Number(dom.year.value),paths=boundaryDebugCapturePaths(activeCountries());if(!paths.length){dom.boundaryDebugStatus.textContent="当前年份没有可导出的疆域。";return}boundaryDebugExportGeometryForItem("svg",{name:`${y} 年全部现有疆域`,year:y,source:"现有地图 SVG",settings:{...boundaryDebugDefaults,opacity:1},paths})}
function boundaryDebugRenderLayer(y){if(!dom.boundaryDebugLayer)return;dom.boundaryDebugLayer.innerHTML="";const target=boundaryDebugTargetMeta(dom.boundaryDebugTarget?.value||boundaryDebugTarget);if(!target||target.type!=="current")return;const paths=boundaryDebugCurrentElements(target.id,y),hasDraft=Object.keys(boundaryDebugDrafts[target.value]||{}).length>0||Object.prototype.hasOwnProperty.call(boundaryDebugTransforms,boundaryDebugStorageKey(target,y));if(!hasDraft)return;const className=target.id==="hejaz"?"boundary-debug-transform-preview":"boundary-debug-outline";boundaryDebugAppendItem({paths:paths.map(path=>({d:path.getAttribute("d")||"",fillRule:path.getAttribute("fill-rule")||"nonzero"}))},boundaryDebugSettings(target,y),className)}
function boundaryDebugDeleteTarget(){const target=boundaryDebugTargetMeta(dom.boundaryDebugTarget?.value||boundaryDebugTarget);if(!target||target.type!=="current")return;delete boundaryDebugTransforms[boundaryDebugStorageKey(target)];delete boundaryDebugDrafts[target.value];boundaryDebugPersist();boundaryDebugTarget="";boundaryDebugPopulateTargets(false);boundaryDebugRenderLayer(Number(dom.year.value));dom.boundaryDebugStatus.textContent="已删除当前疆域的调试参数。"}
function boundaryDebugResetTarget(){const target=boundaryDebugTargetMeta(dom.boundaryDebugTarget?.value||boundaryDebugTarget);if(!target)return;delete boundaryDebugTransforms[boundaryDebugStorageKey(target)];delete boundaryDebugDrafts[target.value];boundaryDebugPersist();boundaryDebugLoadForm();dom.boundaryDebugStatus.textContent="已恢复默认位置与缩放。"}
async function boundaryDebugImportFile(){
  const file=dom.boundaryDebugFile?.files?.[0];if(!file)return;
  const target=boundaryDebugTargetMeta(dom.boundaryDebugTarget?.value||boundaryDebugTarget),y=Number(dom.year.value);
  try{
    const parsed=boundaryDebugParseImport(await file.text(),file.name);
    if(parsed.config){boundaryDebugPersist();boundaryDebugPopulateTargets(false);dom.boundaryDebugStatus.textContent="已载入调试配置。";return}
    if(target?.type!=="current")throw new Error("请先选择当前地图中的疆域，再导入并绑定 SVG");
    const incoming=boundaryDebugImportItem(parsed,file.name);if(!incoming)throw new Error("没有找到可用疆域");
    const period=boundaryDebugReplacementPeriodFor(target.id,y),key=boundaryDebugReplacementKey(target.id,y),reference=boundaryDebugReplacements[key],existing=reference?boundaryDebugItemFor(boundaryDebugReplacementItemTarget(reference)?.target):null,item=existing||incoming;
    boundaryDebugApplyImportedPeriod(item,period,file.name);
    if(existing)Object.assign(existing,{name:item.name,source:incoming.source,sourceFile:file.name,paths:incoming.paths,signature:incoming.signature});
    if(!boundaryDebugImported.some(entry=>entry.key===item.key))boundaryDebugImported.push(item);
    boundaryDebugReplacements[key]={type:"imported",key:item.key,period};
    boundaryDebugTarget=target.value;boundaryDebugPersist();boundaryDebugRebuildMapForReplacement(y);boundaryDebugPopulateTargets(true);
    dom.boundaryDebugStatus.textContent="已绑定“"+item.name+"”到 "+boundaryDebugPeriodLabel(period)+"；该时期内所有相同 SVG 使用同一文件。";return
  }catch(error){dom.boundaryDebugStatus.textContent="导入失败："+(error.message||error)}
}
async function boundaryDebugImportConfig(){const file=dom.boundaryDebugConfigFile?.files?.[0];if(!file)return;try{const value=JSON.parse(await file.text());if(!value||value.version!==2)throw new Error("不是本工具导出的版本 2 配置");boundaryDebugLoadStore(value);boundaryDebugTarget="";boundaryDebugPersist();boundaryDebugPopulateTargets(false);dom.boundaryDebugStatus.textContent="已导入调试配置。"}catch(error){dom.boundaryDebugStatus.textContent=`配置导入失败：${error.message||error}`}}
function boundaryDebugDefaultStoreValue(){const value=boundaryDebugStoreValue(),transforms={...value.transforms};Object.entries(boundaryDebugDrafts).forEach(([targetValue,settings])=>{const target=boundaryDebugTargetMeta(targetValue);if(target?.type==="current")transforms[boundaryDebugStorageKey(target)]={...(transforms[boundaryDebugStorageKey(target)]||{}),...settings}});return{...value,transforms}}
function boundaryDebugResetControlsAfterDefault(){boundaryDebugWriteForm({...boundaryDebugDefaults})}
async function boundaryDebugSaveAsDefault(){const content=JSON.stringify(boundaryDebugDefaultStoreValue(),null,2);dom.boundaryDebugStatus.textContent="正在保存默认配置……";const result=await saveConfigFileAsDefault("mena-boundary-debug.json",content);if(result==="cancelled"){dom.boundaryDebugStatus.textContent="已取消保存默认配置。";return}boundaryDebugResetControlsAfterDefault();dom.boundaryDebugStatus.textContent=result==="file"?"已保存为项目默认配置；滑块已归零，实际参数保持不变。":"已下载默认配置；请将文件放回项目目录后生效。滑块已归零，实际参数保持不变。"}
function boundaryDebugExport(){const blob=new Blob([JSON.stringify(boundaryDebugStoreValue(),null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download="mena-boundary-debug.json";anchor.click();setTimeout(()=>URL.revokeObjectURL(url),0);dom.boundaryDebugStatus.textContent="已导出 mena-boundary-debug.json。"}
const _boundaryDebugCommit=boundaryDebugCommit;boundaryDebugCommit=function(){const ok=_boundaryDebugCommit();const target=boundaryDebugTargetMeta(dom.boundaryDebugTarget?.value||boundaryDebugTarget),y=Number(dom.year.value);if(target?.type==="current"&&boundaryDebugReplacementEntriesForYear(y).some(entry=>entry.id===target.id))boundaryDebugRebuildMapForReplacement(y);return ok};
const _boundaryDebugResetTarget=boundaryDebugResetTarget;boundaryDebugResetTarget=function(){const target=boundaryDebugTargetMeta(dom.boundaryDebugTarget?.value||boundaryDebugTarget),y=Number(dom.year.value);_boundaryDebugResetTarget();if(target?.type==="current"&&boundaryDebugReplacementEntriesForYear(y).some(entry=>entry.id===target.id))boundaryDebugRebuildMapForReplacement(y)};
const _boundaryDebugRenderLayer=boundaryDebugRenderLayer;boundaryDebugRenderLayer=function(y){_boundaryDebugRenderLayer(y);boundaryDebugRenderSchematicReplacements(y)};
const _boundaryDebugDeleteTarget=boundaryDebugDeleteTarget;boundaryDebugDeleteTarget=function(){const target=boundaryDebugTargetMeta(dom.boundaryDebugTarget?.value||boundaryDebugTarget),y=Number(dom.year.value),replacementKey=target?.type==="current"?boundaryDebugReplacementKey(target.id,y):"";_boundaryDebugDeleteTarget();if(replacementKey&&boundaryDebugReplacements[replacementKey]){delete boundaryDebugReplacements[replacementKey];boundaryDebugPersist();boundaryDebugRebuildMapForReplacement(y)}};
function boundaryDebugBindNumericInputs(){[[dom.boundaryDebugScaleX,dom.boundaryDebugScaleXNumber],[dom.boundaryDebugScaleY,dom.boundaryDebugScaleYNumber],[dom.boundaryDebugOffsetX,dom.boundaryDebugOffsetXNumber],[dom.boundaryDebugOffsetY,dom.boundaryDebugOffsetYNumber],[dom.boundaryDebugRotation,dom.boundaryDebugRotationNumber],[dom.boundaryDebugOpacity,dom.boundaryDebugOpacityNumber]].forEach(([range,number])=>{range?.addEventListener("input",()=>{if(number)number.value=range.value;boundaryDebugRefreshDraft()});number?.addEventListener("input",()=>{if(!range||number.value==="")return;const parsed=Number(number.value);if(!Number.isFinite(parsed))return;const min=Number(range.min),max=Number(range.max),value=Math.min(max,Math.max(min,parsed));range.value=String(value);number.value=String(value);boundaryDebugRefreshDraft()})})}
function boundaryDebugBind(){dom.boundaryDebugClose?.addEventListener("click",()=>dom.boundaryDebugDialog.close());dom.boundaryDebugDialog?.addEventListener("click",event=>{if(event.target===dom.boundaryDebugDialog)dom.boundaryDebugDialog.close()});dom.boundaryDebugTarget?.addEventListener("change",boundaryDebugLoadForm);boundaryDebugBindNumericInputs();dom.boundaryDebugImport?.addEventListener("click",boundaryDebugImportFile);dom.boundaryDebugConfigImportButton?.addEventListener("click",()=>dom.boundaryDebugConfigFile?.click());dom.boundaryDebugConfigFile?.addEventListener("change",boundaryDebugImportConfig);dom.boundaryDebugSave?.addEventListener("click",()=>{dom.boundaryDebugStatus.textContent=boundaryDebugCommit()?"已保存调试参数到浏览器。":"浏览器存储不可用，当前预览仍保留。"});dom.boundaryDebugSaveDefault?.addEventListener("click",boundaryDebugSaveAsDefault);dom.boundaryDebugReset?.addEventListener("click",boundaryDebugResetTarget);dom.boundaryDebugDelete?.addEventListener("click",boundaryDebugDeleteTarget);dom.boundaryDebugExportSvg?.addEventListener("click",()=>boundaryDebugExportGeometry("svg"));dom.boundaryDebugExportPaths?.addEventListener("click",()=>boundaryDebugExportGeometry("json"));dom.boundaryDebugExportAllSvg?.addEventListener("click",boundaryDebugExportAllSvg);dom.boundaryDebugExport?.addEventListener("click",boundaryDebugExport)}
const _boundaryDebugPopulateTargetsWithCountries=boundaryDebugPopulateTargets;
boundaryDebugPopulateTargets=function(preserve=true){
  const previous=preserve?(dom.boundaryDebugTarget?.value||boundaryDebugTarget):"";
  _boundaryDebugPopulateTargetsWithCountries(preserve);
  const year=Number(dom.year.value),ids=typeof disputeRegionIdsForYear==="function"?disputeRegionIdsForYear(year):[];
  if(ids.length){const group=document.createElement("optgroup");group.label=`当前争议地区 · ${year}`;ids.forEach(id=>{const period=boundaryDebugPeriodFor(id,year),option=document.createElement("option");option.value=`current:${id}`;option.textContent=boundaryDebugPeriodLabel(period);group.append(option)});dom.boundaryDebugTarget.append(group)}
  const option=[...dom.boundaryDebugTarget.options].find(item=>item.value===previous)||[...dom.boundaryDebugTarget.options].find(item=>item.value===boundaryDebugTarget);
  if(option){dom.boundaryDebugTarget.value=option.value;boundaryDebugTarget=option.value;boundaryDebugLoadForm()}
}
